import { CircleDotIcon, TextIcon, TypeIcon } from "lucide-react";

import { FieldType, type FormField } from "@/types/field";

export const fields: FormField[] = [
  {
    type: FieldType.INPUT,
    name: "Input",
    label: "Your short question",
    placeholder: "pls. provide the response",
    description: "",
    Icon: TypeIcon,
    default: "",
    divisionalInput: "",
    groupHeadInput: "",
    comments: "",
    hodInput: "",
    commentsDivisional: "",
    commentsGroupHead: "",
    appraisalComment: "",
  },
  {
    type: FieldType.TEXTAREA,
    name: "Textarea",
    label: "Your long questions response/list of response",
    placeholder: "",
    description: "Kindly provide the response",
    Icon: TextIcon,
    default: "",
    divisionalInput: "",
    hodInput: "",
    groupHeadInput: "",
    commentsDivisional: "",
    commentsGroupHead: "",
    appraisalComment: "",
  },
  // {
  //   type: FieldType.NUMBER_INPUT,
  //   name: "Number Input",
  //   label: "Age",
  //   placeholder: "24",
  //   description: "Input your age in dog years.",
  //   Icon: HashIcon,
  // },
  // {
  //   type: FieldType.EMAIL,
  //   name: "Email",
  //   label: "Email",
  //   placeholder: "m@example.com",
  //   description: "We won't spam you, we promise.",
  //   Icon: AtSignIcon,
  // },
  // {
  //   type: FieldType.CHECKBOX,
  //   name: "Checkbox",
  //   label: "Use different settings for my mobile devices",
  //   description:
  //     "You can manage your mobile notifications in the mobile settings page.",
  //   Icon: SquareCheckIcon,
  // },
  // {
  //   type: FieldType.SELECT,
  //   name: "Select",
  //   label: "Email",
  //   placeholder: "Select a verified email to display",
  //   description: "You can manage email addresses in your email settings.",
  //   Icon: ChevronsUpDownIcon,
  //   choices: [
  //     {
  //       value: "m@example.com",
  //       label: "m@example.com",
  //     },
  //     {
  //       value: "m@google.com",
  //       label: "m@google.com",
  //     },
  //     {
  //       value: "m@support.com",
  //       label: "m@support.com",
  //     },
  //   ],
  // },

  {
    type: FieldType.RADIO_GROUP,
    name: "Radio Group",
    label: "Your Label/Description of the question ?",
    Icon: CircleDotIcon,
    choices: [
      {
        value: 10,
        label: "Option-1",
      },
      {
        value: 20,
        label: "Option-2",
      },
      {
        value: 30,
        label: "Option-3",
      },
    ],
    default: "",
    divisionalInput: "",
    hodInput: "",
    groupHeadInput: "",
    comments: "",
    commentsDivisional: "",
    commentsGroupHead: "",
    appraisalComment: "",
  },
  // {
  //   type: FieldType.SWITCH,
  //   name: "Switch",
  //   label: "Marketing emails",
  //   description: "Receive emails about new products, features, and more.",
  //   Icon: ToggleLeftIcon,
  // },
  // {
  //   type: FieldType.COMBOBOX,
  //   name: "Combobox",
  //   label: "Language",
  //   Icon: ChevronsUpDownIcon,
  //   description: "This is the language that will be used in the dashboard.",
  //   choices: [
  //     { label: "English", value: "en" },
  //     { label: "French", value: "fr" },
  //     { label: "German", value: "de" },
  //     { label: "Spanish", value: "es" },
  //     { label: "Portuguese", value: "pt" },
  //     { label: "Russian", value: "ru" },
  //     { label: "Japanese", value: "ja" },
  //     { label: "Korean", value: "ko" },
  //     { label: "Chinese", value: "zh" },
  //   ],
  // },
  // {
  //   type: FieldType.SLIDER,
  //   name: "Slider",
  //   label: "Slider",
  //   Icon: SlidersHorizontalIcon,
  //   min: 0,
  //   max: 100,
  //   step: 10,
  //   default: 50,
  // },
];
